default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-yt
  username: postgres
  password: admin

test:
  <<: *default
  database: rails-yt
  username: postgres
  password: admin

production:
  <<: *default
  database: dd2n6emq2ksrsl
  username: ebnpphtsadugqz
  password: cc8e61f1e5ae8fdbde63b95107ed2d05e4b5bf85e12f86937d42d2374f35f29f
  port: 5432
  url: postgres://ebnpphtsadugqz:cc8e61f1e5ae8fdbde63b95107ed2d05e4b5bf85e12f86937d42d2374f35f29f@ec2-54-246-98-119.eu-west-1.compute.amazonaws.com:5432/dd2n6emq2ksrsl